### ISSUE TITLE
Current scope variable name outrules identical outer scope variable name

### ISSUE THREAD

**Issue by dimiterpaskov** [axuno/SmartFormat#133]
If we add a Condition to check if an Object property is null if there are matching property names in the parent and child objects it will pick values from the child object.
```
public class Parent
{
    public string Name { get; set; }
    public string ParentValue { get; set; }
    public Child Child { get; set; }
}

public class Child
{
    public string Name { get; set; }
    public string ChildValue { get; set; }
}

Parent parent = new Parent()
{
    Name = "Parent Name",
    ParentValue = "Parent Value",
    Child = new Child()
    {
        Name = "Child Name",
        ChildValue = "Child Value"
    }
};

string result1 = SmartFormat.Smart.Format("{Child:{ParentValue} - {Child.ChildValue}|}", parent);
string result2 = SmartFormat.Smart.Format("{Child:{Name} - {Child.Name}|}", parent);
```
result1 will output "Parent Value - Child Value" but result2 will output "Child Name - Child Name" instead of "Parent Name - Child Name".

**Comment by axunonb** [comment]
This behavior is built in since a long time.
In short: Even when nesting, you can access **outer scopes**. This applies with and without conditions.
Have a look a this [unit test](https://github.com/axuno/SmartFormat/blob/master/src/SmartFormat.Tests/Core/NestingTests.cs#L39) which exactly matches your example.
In **result1** ```ParentValue``` does not come from the ```Child``` scope, but from the ```Parent``` scope (i.e. outer scope).
In **result2**  ```Child:{Name}``` and ```{Child.Name}``` both refer to the ```Name``` property of ```Child```. Current scope is taken before outer scope.
Does this make sense to you?

**Comment by dimiterpaskov** [comment]
Yes, it makes sense. I guess I assumed that Nesting is not happening for Conditions as I have used them with simple types and was surprised that the scope was changing to the `Child` object.
