### ISSUE TITLE
Plural formatter with singular plural rule

### ISSUE THREAD

**Issue by karljj1** [axuno/SmartFormat#320]
**Is your feature request related to a problem? Please describe.**

What is the correct way to format a string when using the plural formatter with a singular such as Japanese?

I would expect to do "I have {0:plural:{} ringo}" however this produces an error "Formatter named PluralLocalizationFormatter requires at least 2 plural words.". Is this a bug?

**Comment by axunonb** [comment]
Hi Karl, this looks a lot like a bug, that exist since quite a long time:
There is a `Singular` plural rule, that was neglected in this part of the formatter:
https://github.com/axuno/SmartFormat/blob/main/src/SmartFormat/Extensions/PluralLocalizationFormatter.cs#L97-L107
Unfortunately there is no unit test for `Singular` yet.

**Comment by axunonb** [comment]
Wow! https://japaneseparticlesmaster.xyz/plural-in-japanese/

**Comment by axunonb** [comment]
My conclusion after a closer look is:

1. The `PluralLocalizationFormatter` cannot auto-detect, whether it can take over or not, if the number of plural words is only one. This means, that `PluralLocalizationFormatter.CanAutoDetect` should actually be `false` (breaking change).
2. A workaround could be to auto-detect only with 2 or more plural words - see the code below. `Singular` languages would *always* require a named formatter (no breaking change, since `Singular` didn't work at all).

What do you think?

```CSharp
// This extension requires at least two plural words for auto detection
if (pluralWords.Count <= 1)
{
    // Auto detection calls just return a failure to evaluate
    if (string.IsNullOrEmpty(formattingInfo.Placeholder?.FormatterName))
        return false;
}
```

**Comment by huangyedie** [comment]
I want to execute "{{ \"A\":\"{value}\"}}"

**Comment by huangyedie** [comment]
Urgent to use, please reply as soon as possible

**Comment by huangyedie** [comment]
@axunonb

**Comment by axunonb** [comment]
1. `"{{ "A":"{value}"}}"` is not a legal C# expression. 
2. Is 'value' a variable or a literal? 

My best guess is, that `SmartSettings.StringFormatCompatibility` should be changed to `true` in your case (default is `false`).
Please submit an executable code snipped.

**Comment by huangyedie** [comment]
Very good, thank you

**Comment by karljj1** [comment]
> My conclusion after a closer look is:
> 
> 1. The `PluralLocalizationFormatter` cannot auto-detect, whether it can take over or not, if the number of plural words is only one. This means, that `PluralLocalizationFormatter.CanAutoDetect` should actually be `false` (breaking change).
> 2. A workaround could be to auto-detect only with 2 or more plural words - see the code below. `Singular` languages would *always* require a named formatter (no breaking change, since `Singular` didn't work at all).
> 
> What do you think?
> 
> ```CSharp
> // This extension requires at least two plural words for auto detection
> if (pluralWords.Count <= 1)
> {
>     // Auto detection calls just return a failure to evaluate
>     if (string.IsNullOrEmpty(formattingInfo.Placeholder?.FormatterName))
>         return false;
> }
> ```

I think that's fine. I'm trying to encourage our users to be more explicit with their formatter usage. Less pain in the long run 🙂
